CREATE TABLE IF NOT EXISTS words (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    category TEXT NOT NULL,
    word TEXT NOT NULL
);


INSERT INTO words (category, word)
VALUES
('Country', 'POLAND'),
('Country', 'GERMANY'),
('Country', 'FRANCE'),
('Country', 'ITALY'),
('Country', 'UKRAINE'),
('Country', 'BELEARUS'),
('Country', 'RUSSIA'),
('Country', 'AUSTRIA'),
('Country', 'LITHUANIA'),
('Country', 'LATVIA'),
('Country', 'ESTONIA'),
('Country', 'FINLAND'),
('Country', 'SWEDEN'),
('Country', 'NORWAY'),
('Country', 'SPAIN'),
('Country', 'PORTUGAL'),
('Country', 'GREECE'),
('Country', 'ALBANIA'),
('Country', 'MONTENEGRO'),
('Country', 'SERBIA'),
('Country', 'CROATIA'),
('Country', 'DENMARK'),
('Country', 'BELGUM'),
('Country', 'LUXEMBOURG'),
('Country', 'LIECHTENSTEIN'),
('Country', 'GREAT BRITAN'),
('Country', 'THE NETHERLANDS'),
('Country', 'JAPAN'),
('Country', 'CHINA'),
('Country', 'VIETNAM'),
('Country', 'LAOS'),
('Country', 'AUSTRALIA'),
('Country', 'NEW ZELAND'),
('Country', 'EGYPT'),
('Country', 'SOUTH AFRICA'),
('Fruit', 'APPLE'),
('Fruit', 'CHERRY'),
('Fruit', 'ORANGE'),
('Fruit', 'GRAPE'),
('Fruit', 'BANANNA'),
('Fruit', 'MELON'),
('Fruit', 'PEACH'),
('Fruit', 'PLUM'),
('Fruit', 'RASPBERRY'),
('Fruit', 'BLACKBERRY'),
('Fruit', 'KIWI'),
('Sport', 'BASKETBALL'),
('Sport', 'GOLF'),
('Sport', 'FOOTBALL'),
('Sport', 'SWIMMING'),
('Sport', 'SKIKING'),
('Thing', 'WATCH'),
('Thing', 'LAPTOP'),
('Thing', 'WALLET'),
('Thing', 'PENSIL'),
('Thing', 'BOTTLE'),
('Thing', 'CARPET'),
('Thing', 'LAMP'),
('Thing', 'REMOTE'),
('Thing', 'SCISORS');

